spring:
# thymeleaf
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
    mode: HTML
    content-type: text/html

#  激活模式
  profiles:
    active: dev

  # pagehelper(https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md)
  pagehelper:
    offset-as-page-num: true
    helper-dialect: mysql
    row-bounds-with-count: true
    reasonable: true
#    如果pageSize=0，则查询出所有结果
    pageSizeZero: true

# 表示所有的访问都经过静态资源路径；
  mvc:
    static-path-pattern: /**
# 加入所有静态资源路径（覆盖默认配置）
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/json/,classpath:/public/,file:${web.updPath},file:${web.dwdPath},file:${web.imgPath}