# 端口
server:
  port: 80
# 文件上传地址
web:
  updPath: D:/WorkStation/Mims/upd-prd/
  dwdPath: D:/WorkStation/Mims/dwd-prd/

# 数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mims_prd?useSSL=true
