server:
  port: 80
# 数据源
spring:
# thymeleaf
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
    mode: HTML
    content-type: text/html
#  激活模式
  profiles:
    active: dev